version: '2'

services:
  caNetflix:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-netflix
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.netflix.myapp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/584c1528b8a48e259a1077df486b7a45cc39e7382a66f95afccbdd123219b57c_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.netflix.myapp.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/584c1528b8a48e259a1077df486b7a45cc39e7382a66f95afccbdd123219b57c_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/netflix.myapp.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerNetflix

  caHbo:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hbo
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hbo.myapp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8a02459aa8b6ec82ebf211ca39eb3490a9771945cbc12ba1f365ec0bf331d539_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hbo.myapp.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8a02459aa8b6ec82ebf211ca39eb3490a9771945cbc12ba1f365ec0bf331d539_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hbo.myapp.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHbo

  orderer.myapp.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.myapp.com
    container_name: orderer.myapp.com

  peer0.netflix.myapp.com:
    container_name: peer0.netflix.myapp.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.netflix.myapp.com

  peer0.hbo.myapp.com:
    container_name: peer0.hbo.myapp.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hbo.myapp.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.netflix.myapp.com:7051
      - CORE_PEER_LOCALMSPID=netflixMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/peers/peer0.netflix.myapp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/netflix.myapp.com/users/Admin@netflix.myapp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincodes/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.myapp.com
      - peer0.netflix.myapp.com
      - peer0.hbo.myapp.com
